(function(){function l(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function n(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(c)return c.call(a);if("number"==typeof a.length)return{next:l(a)};throw Error(String(a)+" is not an iterable or ArrayLike");};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var p=this||self;function q(a){return a};/*

 SPDX-License-Identifier: Apache-2.0
*/
function t(a){return{valueOf:a}.valueOf()};var u;var v=t(function(){return"function"===typeof URL}),w=["data:","http:","https:","mailto:","ftp:"];var x={};function y(a){this.g=a}y.prototype.toString=function(){return this.g.toString()};function z(a){return a instanceof y&&a.constructor===y?a.g:"type_error:SafeHtml"}function A(a){if(void 0===u){var c=null;var b=p.trustedTypes;if(b&&b.createPolicy){try{c=b.createPolicy("goog#html",{createHTML:q,createScript:q,createScriptURL:q})}catch(e){p.console&&p.console.error(e.message)}u=c}else u=c}a=(c=u)?c.createHTML(a):a;return new y(a,x)};function C(a,c){var b=c.createRange();b.selectNode(c.body);a=A(a);return b.createContextualFragment(z(a))};function D(a){a=a.nodeName;return"string"===typeof a?a:"FORM"}function E(a){a=a.nodeType;return 1===a||"number"!==typeof a};function F(a,c,b,e){this.i=a;this.g=c;this.j=b;this.l=e};var G=new F(new Set("ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" ")),
new Map([["A",new Map([["href",{h:2}]])],["AREA",new Map([["href",{h:2}]])],["LINK",new Map([["href",{h:2,conditions:new Map([["rel",new Set("alternate author bookmark canonical cite help icon license next prefetch dns-prefetch prerender preconnect preload prev search subresource".split(" "))]])}]])],["SOURCE",new Map([["src",{h:1}],["srcset",{h:1}]])],["IMG",new Map([["src",{h:1}],["srcset",{h:1}]])],["VIDEO",new Map([["src",{h:1}]])],["AUDIO",new Map([["src",{h:1}]])]]),new Set("title aria-atomic aria-autocomplete aria-busy aria-checked aria-current aria-disabled aria-dropeffect aria-expanded aria-haspopup aria-hidden aria-invalid aria-label aria-level aria-live aria-multiline aria-multiselectable aria-orientation aria-posinset aria-pressed aria-readonly aria-relevant aria-required aria-selected aria-setsize aria-sort aria-valuemax aria-valuemin aria-valuenow aria-valuetext alt align autocapitalize autocomplete autocorrect autofocus autoplay bgcolor border cellpadding cellspacing checked color cols colspan controls datetime disabled download draggable enctype face formenctype frameborder height hreflang hidden ismap label lang loop max maxlength media minlength min multiple muted nonce open placeholder preload rel required reversed role rows rowspan selected shape size sizes slot span spellcheck start step summary translate type valign value width wrap itemscope itemtype itemid itemprop itemref".split(" ")),
new Map([["dir",{h:3,conditions:t(function(){return new Map([["dir",new Set(["auto","ltr","rtl"])]])})}],["async",{h:3,conditions:t(function(){return new Map([["async",new Set(["async"])]])})}],["cite",{h:2}],["loading",{h:3,conditions:t(function(){return new Map([["loading",new Set(["eager","lazy"])]])})}],["poster",{h:2}],["target",{h:3,conditions:t(function(){return new Map([["target",new Set(["_self","_blank"])]])})}]]));function H(a){this.g=a}
function I(a,c,b){c=C(c,b);c=document.createTreeWalker(c,5,function(d){if(3===d.nodeType)d=1;else if(E(d))if(d=D(d),null===d)d=2;else{var g=a.g;d="FORM"!==d&&(g.i.has(d)||g.g.has(d))?1:2}else d=2;return d});for(var e=c.nextNode(),m=b.createDocumentFragment(),f=m;null!==e;){var h=void 0;if(3===e.nodeType)h=document.createTextNode(e.data);else if(E(e))h=J(a,e,b);else throw Error("");f.appendChild(h);if(e=c.firstChild())f=h;else for(;!(e=c.nextSibling())&&(e=c.parentNode());)f=f.parentNode}return m}
function J(a,c,b){var e=D(c);b=b.createElement(e);c=c.attributes;for(var m=n(c),f=m.next();!f.done;f=m.next()){var h=f.value;f=h.name;h=h.value;var d=a.g;var g=d.g.get(e);d=(null==g?0:g.has(f))?g.get(f):d.j.has(f)?{h:1}:(d=d.l.get(f))?d:{h:0};a:{if(g=d.conditions){g=n(g);for(var k=g.next();!k.done;k=g.next()){var r=n(k.value);k=r.next().value;r=r.next().value;var B=void 0;if((k=null==(B=c.getNamedItem(k))?void 0:B.value)&&!r.has(k)){g=!1;break a}}}g=!0}if(g)switch(d.h){case 1:K(b,f,h);break;case 2:a:if(d=
void 0,v){try{d=new URL(h)}catch(L){d="https:";break a}d=d.protocol}else b:{d=document.createElement("a");try{d.href=h}catch(L){d=void 0;break b}d=d.protocol;d=":"===d||""===d?"https:":d}K(b,f,void 0!==d&&-1!==w.indexOf(d.toLowerCase())?h:"about:invalid#zClosurez");break;case 3:K(b,f,h.toLowerCase());break;case 4:K(b,f,h)}}return b}function K(a,c,b){a.setAttribute(c,b)};function M(){this.i=!1;this.g=G};window.gwd=window.gwd||{};window.gwd.binders=window.gwd.binders||{};
window.gwd.binders.html=function(a,c){if("undefined"!=typeof c){var b=document.querySelector("gwd-text-helper");b&&b.saveInitialText(a);b=new M;var e=new Map(b.g.l);e.set("style",{h:4});b.g=new F(b.g.i,b.g.g,b.g.j,e);e=new Set(b.g.j);e.add("id");b.g=new F(b.g.i,b.g.g,e,b.g.l);e=new Set(b.g.j);e.add("class");b.g=new F(b.g.i,b.g.g,e,b.g.l);if(b.i)throw Error("this sanitizer has already called build");b.i=!0;e=new H(b.g);b=document.implementation.createHTMLDocument("");c=I(e,c,b);b=b.body;b.appendChild(c);
c=(new XMLSerializer).serializeToString(b);c=c.slice(c.indexOf(">")+1,c.lastIndexOf("</"));c=A(c);if(1===a.nodeType&&(b=a.tagName,"SCRIPT"===b||"STYLE"===b))throw Error("");a.innerHTML=z(c)}};}).call(this);
