import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import Head from "next/head"; // Import Head component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Grill Bot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Head>
            {/* Add the favicon link */}
            <link rel="icon" href="/favicon.ico" type="image/x-icon" />

            {/* You can use other formats like .png or .svg as well */}
          </Head>
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 4000,
              success: {
                style: {
                  background: "#4CAF50",
                  color: "#fff",
                  fontWeight: "bold",
                },
                iconTheme: { primary: "#fff", secondary: "#4CAF50" },
              },
              error: {
                style: {
                  background: "#D32F2F",
                  color: "#fff",
                },
              },
            }}
          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
